### ISSUE TITLE
機能要件洗い出し

### ISSUE THREAD

**Issue by gennei** [CoffeeAndCakes/waffle#2]
@kyonya 

アプリでできることを書き出す。
このアプリでできることを列挙してください。

**Comment by kyonya** [comment]
細かい部分は端折りつつ、この内容から削れるとこ削ってく。


### 1.ダイス機能
・ダイスを振る機能がある
・ダイスの種類は以下を用意する
　　a.1~3
　　b.
　　c.
　　d.


### 2.キャラシート作成機能
・決められたステータス項目にダイス判定を行い、項目に数値を与える
・ダイスを振らずに直接入力も可
・数値のみ、文字列可は項目ごとに異なる
・ステータス項目は以下に分類される
　　a.生まれ・能力値
　　b.SAN値
　　c.技能
　　d.戦闘・武器・防具
　　e.所持品・所持金
　　d.パーソナルデータ
　　e.アイコン
　　


### 3.判定可ダイス機能（技能ロール）
・設定したステータスとダイスを比較し、成功・失敗の判定を行う
・クリティカル（D100で5以下）・ファンブル（D100で96以上）の判定を行う（例外あり）
・判定を行う項目をカタログで確認でき、選ぶことができる



### 4.固定文字列ダイス機能（SAN値チェック・狂気ロール）
・ステータス：SAN値とダイスを比較し、成功・失敗の判定を行う
・ダイスを振り、ステータス：SAN値から出た目をマイナスする、同時にステータス：クトゥルフ神話知識にプラスする
・アイディア値とダイスを比較し、成功・失敗の判定を行う
・「一時的な狂気」用意した固定文字列から、一つ引く（ダイス目の文字列ver）
・「不定の狂気」用意した固定文字列から、一つ引く（ダイス目の文字列ver）



### 5.ログ機能
・全てのダイス、ステータスの変更が行われたログを見ることができる
（ログの変更、削除機能は持たせない）



### 6.セーブ機能
・1,2,3のスロットがあり、初期は1スロットにログインしている状態
・ログイン状態のスロットで行ったキャラクターシート、ログ情報が保存されていく
・自動保存（オートセーブ状態）
・トップ画面から別のスロットに移動することができる
・キャラシートを削除することができる

**Comment by gennei** [comment]
いいですね〜

**Comment by gennei** [comment]
いったんこれで進めるでよさそう

**Comment by gennei** [comment]
https://github.com/CoffeeAndCakes/waffle/wiki に移したので閉じます。
