### ISSUE TITLE
Andorid Studio の環境を用意する

### ISSUE THREAD

**Issue by gennei** [CoffeeAndCakes/waffle#3]
@kyonya 

下記のページを見ればいけそう
Android Studio 2.2(2.2.2)の導入(前編)
http://qiita.com/ygenda/items/d0f9386cc764b8b441dd

**Comment by gennei** [comment]
### Mac
mac は下記で完了した。

```
$brew install android-studio
```

**Comment by gennei** [comment]
インストールが完了したら終わり

**Comment by kyonya** [comment]
インスコは先週したけど、win環境下でテストとかまだしてないっす

**Comment by gennei** [comment]
Mac 環境では下記PRで動くことを確認した。
https://github.com/CoffeeAndCakes/waffle/pull/6

**Comment by gennei** [comment]
環境の用意はできているので終わり
